import { IncomingForm } from 'formidable';
import fs from 'fs';
import OpenAI from 'openai';

// Initialize OpenAI
let openai;
if (process.env.OPENAI_API_KEY) {
  openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });
} else {
  console.error('Missing OPENAI_API_KEY');
}

export const config = {
  api: {
    bodyParser: false,
  },
};

export default async function handler(req, res) {
  console.log('=== API ANALYZE CALLED ===');
  
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    console.log('Parsing form data...');
    
    // Parse the uploaded file
    const data = await new Promise((resolve, reject) => {
      const form = new IncomingForm();
      form.parse(req, (err, fields, files) => {
        if (err) reject(err);
        resolve({ fields, files });
      });
    });

    const { files } = data;
    
    if (!files.file || !files.file[0]) {
      return res.status(400).json({ error: 'No file uploaded' });
    }

    const file = files.file[0];
    console.log('File received:', file.originalFilename);

    // Create a simple analysis (bypass AI for now to test)
    const analysis = `FINANCIAL ANALYSIS REPORT
=========================

File: ${file.originalFilename}
Date: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY:
• File successfully processed by Analyst.ai
• Basic financial analysis completed
• Ready for management review

KEY FINDINGS:
1. Revenue trends analyzed
2. Profitability metrics calculated
3. Cash flow position assessed

NEXT STEPS:
• Review the detailed analysis
• Share with management team
• Schedule follow-up discussion

---
Generated by Analyst.ai
Your AI-powered financial analysis tool
`;

    console.log('Sending analysis response...');
    
    // Send back as a downloadable text file
    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename="analysis-${Date.now()}.txt"`);
    res.send(analysis);

  } catch (error) {
    console.error('API Error:', error);
    // Return proper JSON error
    res.status(500).json({ 
      error: 'Analysis failed',
      message: error.message 
    });
  }
}
